### ISSUE TITLE
Conda found conflicts

### ISSUE THREAD

**Issue by CHR-ray** [orpatashnik/local-prompt-mixing#2]
<img width="505" alt="image" src="https://github.com/orpatashnik/local-prompt-mixing/assets/75762846/039df530-e3fa-4394-98dd-3ca02ff5fb24">
Hello, I am trying to install the dependencies from lpm_env.yml, but I get this warning from conda and get stuck here, can you check it? (And after this warning, conda throw a very very long conflict list....)

**Comment by orpatashnik** [comment]
Hi,
Can you please try to install the requirements from this file https://github.com/orpatashnik/local-prompt-mixing/blob/main/requirements.txt?
Let me know if you still have any issues

**Comment by CHR-ray** [comment]
Thank you, it works!
