### ISSUE TITLE
Background Word not found

### ISSUE THREAD

**Issue by sauradip** [orpatashnik/local-prompt-mixing#3]
Hi ,

Thanks for opensourcing the amazing work. 

I tried using the following command and ran into some error

`python main.py --seed 48 --prompt "A woman wearing a {word}, a cropped top, and a white sneaker" --object_of_interest "short jean skirt" --background_nouns=["woman"] --proxy_words=["long skirt","long yellow trousers"]`

and i got the following error 

<img width="1061" alt="Screenshot 2023-12-14 at 8 09 14 AM" src="https://github.com/orpatashnik/local-prompt-mixing/assets/23197350/d3fbdba4-e029-4006-a838-f8803f130d5a">

Kindly help ! Thanks in advance

**Comment by orpatashnik** [comment]
Thanks for your interest in our work!
we assume that the only separators between words are spaces. Removing the ',' should fix this problem 🙂
